# Generated by Django 4.2.10 on 2026-03-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookmark',
            new_name='bookmarks_user_id_2ce2db_idx',
            old_name='bookmarks_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_lecture_668cde_idx',
            old_name='comments_lecture_created_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comments_user_id_8613ff_idx',
            old_name='comments_user_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='departments_slug_b4a8c1_idx',
            old_name='departments_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='departments_code_9f933a_idx',
            old_name='departments_code_idx',
        ),
        migrations.RenameIndex(
            model_name='progresstracking',
            new_name='progress_tr_user_id_758278_idx',
            old_name='progress_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='progresstracking',
            new_name='progress_tr_lecture_6cb3fb_idx',
            old_name='progress_lecture_user_idx',
        ),
        migrations.RenameIndex(
            model_name='semester',
            new_name='semesters_departm_214f7e_idx',
            old_name='semesters_department_order_idx',
        ),
        migrations.RenameIndex(
            model_name='semester',
            new_name='semesters_slug_803d5b_idx',
            old_name='semesters_slug_idx',
        ),
    ]
