# Generated by Django 4.2.10 on 2026-03-24 05:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_add_academic_structure'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_departm_ffc7ef_idx',
            old_name='courses_dept_semester_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_teacher_e891c2_idx',
            old_name='courses_teacher_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
