# Generated by Django 4.2.10 on 2026-03-25 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_update_course_structure'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_is_publ_728c25_idx',
            old_name='courses_is_publ_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='courses_course__5da9ef_idx',
            old_name='courses_course_c_idx',
        ),
    ]
