# Generated by Django 4.2.10 on 2026-03-25 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_add_content_item_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('slide', 'Presentation Slides'), ('text', 'Text Notes'), ('link', 'External Link')], help_text='Type of content', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within module')),
                ('video_file', models.FileField(blank=True, help_text='Uploaded video file', null=True, upload_to='content/videos/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)')),
                ('hls_playlist_url', models.URLField(blank=True, help_text='HLS streaming URL (for uploaded videos)')),
                ('hls_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True)),
                ('file', models.FileField(blank=True, help_text='PDF or Slide file', null=True, upload_to='content/files/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('content_text', models.TextField(blank=True, help_text='Rich text content for notes')),
                ('external_url', models.URLField(blank=True, help_text='External resource URL')),
                ('description', models.TextField(blank=True)),
                ('is_downloadable', models.BooleanField(default=True, help_text='Allow students to download this content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(help_text='Module this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='courses.module')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_items',
                'ordering': ['module', 'order', 'created_at'],
                'indexes': [models.Index(fields=['module', 'order'], name='content_ite_module__a3346e_idx'), models.Index(fields=['content_type'], name='content_ite_content_380b34_idx')],
                'unique_together': {('module', 'order')},
            },
        ),
    ]
