# Generated by Django 4.2.10 on 2026-03-26 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_add_content_item_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module_progress',
                'indexes': [models.Index(fields=['user', 'module'], name='module_prog_user_id_f26fa8_idx'), models.Index(fields=['module', 'is_completed'], name='module_prog_module__22c6d2_idx')],
                'unique_together': {('user', 'module')},
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_modules', models.PositiveIntegerField(default=0)),
                ('total_modules', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_progress',
                'indexes': [models.Index(fields=['user', 'course'], name='course_prog_user_id_05364d_idx'), models.Index(fields=['user', 'last_accessed'], name='course_prog_user_id_39d45b_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_viewed', models.BooleanField(default=False)),
                ('watch_duration_seconds', models.PositiveIntegerField(default=0, help_text='For videos: how long user watched')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.contentitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_progress',
                'indexes': [models.Index(fields=['user', 'content_item'], name='content_pro_user_id_79a9f7_idx'), models.Index(fields=['content_item', 'is_viewed'], name='content_pro_content_0fb275_idx')],
                'unique_together': {('user', 'content_item')},
            },
        ),
    ]
